name: CadZinho CI

on: workflow_dispatch

jobs:
  linux-build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: sudo apt-get install --yes libsdl2-dev libglvnd-dev libglew-dev
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: get make file
      run: cp linux/Makefile ./Makefile
    - name: make
      run: make
    - run: |
        mkdir ./linux/CadZinho/bin
        cp ./cadzinho ./linux/CadZinho/bin/cadzinho
    - name: create archive
      run: |
        cd linux
        zip -r linux CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: linux/linux.zip
        retention-days: 5
        
  macos-build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: brew install sdl2 lua mesa-glu glew dylibbundler
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      run: rm lua-5.4.4/src/lua.c lua-5.4.4/src/luac.c
    - name: copy lua sources 
      run: cp lua-5.4.4/src/* ./src/
    - name: get make file
      run: cp macos/Makefile ./Makefile
    - name: make
      run: make
    - run: mkdir ./macos/CadZinho.app/Contents/MacOS
    - run: cp ./cadzinho ./macos/CadZinho.app/Contents/MacOS/cadzinho
    - name: fix dependencies
      run: dylibbundler -od -b -x ./macos/CadZinho.app/Contents/MacOS/cadzinho -d ./macos/CadZinho.app/Contents/libs/
    - name: create archive
      run: |
        cd macos
        zip -r macos ./CadZinho.app/
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: macos/macos.zip
        retention-days: 5
  
  windows-build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            p7zip
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-SDL2
            mingw64/mingw-w64-x86_64-glew
            mingw64/mingw-w64-x86_64-lua
    - uses: actions/checkout@v3
    - name: get make file and resources
      run: cp windows/* ./
    - name: make
      run: make
    - run: |
        mkdir CadZinho
        cp cadzinho.exe CadZinho/
        cp windows/cadzinho.ico CadZinho/
        cp /mingw64/bin/SDL2.dll CadZinho/
        cp /mingw64/bin/glew32.dll CadZinho/
        cp /mingw64/bin/lua54.dll CadZinho/
    - name: create archive
      run: 7z a windows.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: windows.zip
        retention-days: 5
  release:
    needs: [linux-build, macos-build, windows-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: uploads
      - uses: softprops/action-gh-release@v0.1.14
        with:
          tag_name: 0.2.0
          draft: true
          files: |
            linux.zip
            macos.zip
            windows.zip
