name: build CadZinho for windows

on:
  push:
    branches: [ "opengl" ]

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-SDL2
            mingw64/mingw-w64-x86_64-glew
            mingw64/mingw-w64-x86_64-lua
    - uses: actions/checkout@v3
    - name: make
      run: make
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: CadZinho
        path: cadzinho.exe
        retention-days: 5
    - name: Sleep for 30 seconds
      run: Start-Sleep -s 30
      shell: powershell
    - name: Create a desktop screenshot
      uses: OrbitalOwen/desktop-screenshot-action@0.1
      with:
        file-name: screenshot.jpg
    - name: Upload the screenshot
      uses: actions/upload-artifact@v3
      with:
        name: CadZinho
        path: screenshot.jpg
        retention-days: 5
