name: build CadZinho for windows

on:
  push:
    branches: [ "opengl" ]

jobs:
  build:
    defaults:
      run:
        shell: msys2 {0}
    runs-on: windows-latest

    steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-SDL2
            mingw64/mingw-w64-x86_64-glew
            mingw64/mingw-w64-x86_64-lua
    - uses: actions/checkout@v3
    - name: make
      run: make
