name: Test

on: workflow_dispatch

jobs:
  win:
  
   defaults:
      run:
        shell: msys2 {0}
   runs-on: windows-latest

   steps:
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
          update: true
          install: >-
            base-devel
            git
            gcc
            make
            p7zip
            mingw-w64-x86_64-toolchain
            mingw64/mingw-w64-x86_64-SDL2
            mingw64/mingw-w64-x86_64-glew
    - uses: actions/checkout@v3
    - name: download lua source
      run: curl -R -O http://www.lua.org/ftp/lua-5.4.4.tar.gz
    - name: extract lua
      run: tar zxf lua-5.4.4.tar.gz
    - name: remove main in lua
      shell: cmd
      run: |
        cd lua-5.4.4\src
        del lua.c 
        del luac.c
    - name: copy lua sources 
      run: cp ./lua-5.4.4/src/* ./src/
    - name: get make file and resources
      run: cp windows/* ./
    - name: make
      run: make
    - name: take a screenshot
      shell: cmd
      run: |
        cd .github/workflows/
        npm install screenshot-desktop
        node test.js
        dir
    - run: ls .github/workflows/
    - run: |
        mkdir CadZinho
        cp cadzinho.exe CadZinho/
        cp windows/cadzinho.ico CadZinho/
        cp /mingw64/bin/SDL2.dll CadZinho/
        cp /mingw64/bin/glew32.dll CadZinho/
        cp LICENSE.txt CadZinho/
        cp .github/workflows/test.png CadZinho/
    - name: create archive
      run: 7z a windows.zip CadZinho
    - name: Upload the result
      uses: actions/upload-artifact@v3
      with:
        name: uploads
        path: windows.zip
        retention-days: 5
